version: "2"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RABBIT_SLEEP: 5
      BROKER_URL: "amqp://guest:guest@rabbitmq:5672/"
