version: "2"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    build:
      context: .
      dockerfile: Dockerfile_producer
  consumer:
    build:
      context: .
      dockerfile: Dockerfile_consumer